- Updated pre-commit hooks. - Changed tests to use Bats, updated README. - Removed dependency on Make, updated README, TravisCI. - Added usage when called after sourced. - Cleaner is_sourced alias. - No longer cd into the certs directory. - Fixed several small issues, bugs and edge cases.

diff --git a/bundle_certs b/bundle_certs
--- a/bundle_certs
+++ b/bundle_certs
@@ -3,7 +3,7 @@
 
 # Check if the script is being sourced or not.
 # shellcheck disable=SC2142
-alias is_sourced='[ "$_" != "$0" ] && expr "$-" : ".*i.*" > /dev/null'
+alias is_sourced='[ "$_" != "$0" ] && [ "${-#*i}" != "$-" ]'
 
 # Returns the subject hash of the certificate path provided.
 alias subject_hash='openssl x509 -noout -subject_hash -in'
@@ -61,38 +61,41 @@ unbundle_cert () {
 }
 
 bundle_certs () {
-    local issuer issued ordered_certs filename
+    local filename issuer issued bundle
+    if [ $# -eq 0 ]
+    then
+        echo "Usage: bundle_certs filename [filename2 [filename3 ...]]" >> /dev/stderr
+        return 1
+    fi
     for filename in "$@"
     do
         [ -f "$filename" ] && unbundle_cert "$filename"
     done
-    cd certs
-    issuer="$(find_root_cert "*")"
+    issuer="$(find_root_cert certs/*)"
     if [ -z "$issuer" ]
     then
-        echo "Failed to find root certificate." > /dev/stderr
-        exit 1
+        echo "Failed to find root certificate." >> /dev/stderr
+        return 1
     fi
-    issued="$(find_cert_by_issuer_hash "$issuer" "*")"
+    issued="$(find_cert_by_issuer_hash "$(basename "$issuer")" certs/*)"
+    bundle="$(cat "$issued")"
     while [ -n "$issued" ]
     do
-        ordered_certs="$issued $ordered_certs"
         issuer="$issued"
-        issued="$(find_cert_by_issuer_hash "$issuer" "*")"
+        issued="$(find_cert_by_issuer_hash "$(basename "$issuer")" certs/*)"
+        [ -n "$issued" ] && bundle="$(echo "${bundle:-}"; cat "$issued")"
     done
-    cat "$ordered_certs"
-    cd ..
+    echo "$bundle"
     rm -r certs
 }
 
-
-if ! is_sourced
+if ! (is_sourced)
 then
     set -eu
     if [ $# -eq 0 ]
     then
-        echo "Usage: $0 filename [filename2 [filename3 ...]]" > /dev/stderr
-        exit 1
+        echo "Usage: $(basename "$0") filename [filename2 [filename3 ...]]" >> /dev/stderr
+        return 1
     else
         bundle_certs "$@"
     fi
